### ISSUE TITLE
Problem with pyopenssl==17.2.0

### ISSUE THREAD

**Issue by mariobranco** [SpiderLabs/ikeforce#10]
If you are having this problem.

` ./ikeforce.py [HOST_IP] -a`
[+]Program started in Transform Set Enumeration Mode
[+]Checking for acceptable Transforms

Accepted (AM) Transform Sets

Traceback (most recent call last):
  File "./ikeforce.py", line 307, in <module>
    iCookie = ikeneg.secRandom(8).encode('hex')
  File "/home/master/git/ikeforce/ikeclient.py", line 46, in secRandom
    randomBytes = OpenSSL.rand.bytes(bytes)
AttributeError: 'module' object has no attribute 'rand'

**You can fix buy running this command**

` pip install 'pyopenssl==17.2.0'`

**Comment by dnet** [comment]
See also #11
