### ISSUE TITLE
Crash while running brute force

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/ikeforce#3]
I attempted to run a brute force and got the following error:

root@wopr:/opt/ikeforce# ./ikeforce.py 1.2.3.4 -b -k *******\* -i DefaultRAGroup -u cisco -w 500-worst-passwords.txt '

[+]Program started in XAUTH Brute Force Mode
[+]Single user provided - brute forcing passwords for user: cisco
Press return for a status update
Traceback (most recent call last):
  File "./ikeforce.py", line 1876, in <module>
    respDict,vidHolder = ikeHandling.main(packets[-1],encType,hashType,encKey,initIV,curIV)
ValueError: too many values to unpack

**Comment by ghost** [comment]
More context from --debug:
Parsing Mode Config Payload:
Next Payload: NONE
Payload Length: 20
Mode Config Message Type: ISAKMP_CFG_REQUEST
Mode Config ID: 0

Mode CFG Payload: c088000040890000408a0000
Mode Config Attribute Type: XAUTH_TYPE (16520)
Mode Config Attribute Value: 0
Mode Config Attribute Type: XAUTH_USER_NAME (16521)
Mode Config Attribute Length: 0
Mode Config Attribute Value:  ()
Mode Config Attribute Type: XAUTH_USER_PASSWORD (16522)
Mode Config Attribute Length: 0
Mode Config Attribute Value:  ()
Traceback (most recent call last):
  File "./ikeforce.py", line 1074, in <module>
    respDict,vidHolder = ikeHandling.main(packets[-1],encType,hashType,encKey,initIV,curIV)
ValueError: too many values to unpack

**Comment by f0cker** [comment]
Thanks for reporting this. I'll see if I can track it down over the weekend, is the crash reproduced every time you run it?

**Comment by ghost** [comment]
I tried various ways of running it and it kept crashing. Based on the debug looks like it wasn't parsing the packets right. Perhaps there is a variance in the structure.
I'll do my best to get you some pcaps but it's a client device so I'll have to sanatize a bit

Get Outlook for iOShttps://aka.ms/o0ukef

On Fri, Sep 16, 2016 at 7:01 AM -0400, "f0cker" <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks for reporting this. I'll see if I can track it down over the weekend, is the crash reproduced every time you run it?

##
